export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'; 
export const UPDATE_USER_EMPTY = 'UPDATE_USER_EMPTY'; 

export const UPDATE_ERROR_MENSAJE = 'UPDATE_ERROR_MENSAJE';

export const UPDATE_CARGANDO = 'UPDATE_CARGANDO';